Add gcp provider support
crc-org/crc-cloud pull request #141
Opened 2023-09-15 12:41 UTC by praveenkumar

2023-09-15 12:56 UTC, adrianriobo requested changes

2023-09-15 12:56 UTC, adrianriobo commented on pkg/provider/gcp/create-instance.go
> +					"22", "443", "6443", "80",
Can we create some common pkg with this information, so each provider will get values from there and will create the resources it need based on those values... (aws sgs, gcp firewall...).

Otherwise if for whatever reason we want to add some other port in the future we need to go provider by provider

2023-09-15 12:56 UTC, adrianriobo commented on pkg/provider/gcp/create-instance.go
> +func createKey(ctx *pulumi.Context) (*tls.PrivateKey, error) {
same here move to common pkg and reuse from all providers

2023-09-15 12:56 UTC, adrianriobo commented on pkg/provider/gcp/gcp.go
> +		Version: "v6.65.0"}
need this version at Containerfile as the other plugins 
(i.e. https://github.com/crc-org/crc-cloud/blob/eb143b96ac197fd50a2a0f8f91772cd080c6d8b4/oci/Containerfile#L40)

then also add the plugin installation cmd 
(i.e. https://github.com/crc-org/crc-cloud/blob/eb143b96ac197fd50a2a0f8f91772cd080c6d8b4/oci/Containerfile#L48)

2023-09-15 14:58 UTC, praveenkumar commented on pkg/provider/gcp/create-instance.go
> +					"22", "443", "6443", "80",
we can make port as part of constants and use it for each provider.

2023-09-15 15:00 UTC, praveenkumar commented on pkg/provider/gcp/create-instance.go
> +func createKey(ctx *pulumi.Context) (*tls.PrivateKey, error) {
for aws it is different signature `func createKey(ctx *pulumi.Context) (*tls.PrivateKey, *ec2.KeyPair, error)` but yes some of it can be consumed for each provider.

2023-09-15 15:00 UTC, praveenkumar commented on pkg/provider/gcp/gcp.go
> +		Version: "v6.65.0"}
Ack, will update that.

2023-09-15 15:40 UTC, praveenkumar commented on pkg/provider/gcp/create-instance.go
> +					"22", "443", "6443", "80",
Updated

2023-09-15 15:40 UTC, praveenkumar commented on pkg/provider/gcp/create-instance.go
> +func createKey(ctx *pulumi.Context) (*tls.PrivateKey, error) {
updated.

2023-09-15 15:41 UTC, praveenkumar commented on pkg/provider/gcp/gcp.go
> +		Version: "v6.65.0"}
Done.

2023-09-18 08:04 UTC, adrianriobo commented
Can we add some README content on how to use the gcp, some code snippet on how to invoke the container or the binary? Envs required....

Also did you give a try to build a container and run from it AFAIK we will need to add the gcp cli to the container as well...may at https://github.com/crc-org/crc-cloud/blob/main/requirements.txt

2023-12-13 07:39 UTC, praveenkumar commented
> Can we add some README content on how to use the gcp, some code snippet on how to invoke the container or the binary? Envs required....

Yes I updated the README which have all the steps and usecase.
 
> Also did you give a try to build a container and run from it AFAIK we will need to add the gcp cli to the container as well...may at https://github.com/crc-org/crc-cloud/blob/main/requirements.txt

gcp cli added as part of container image, I am not sure why `requirements.txt` is there ?

2023-12-13 10:18 UTC, adrianriobo commented
>  gcp cli added as part of container image, I am not sure why requirements.txt is there ?

need to add both the pulumi plugin for gpc and the gcp cli I only see the the pulumi plugin, also that requirements is a way to manage tooling through `pip` if I am not wrong, so maybe you can just add a new line  for the gcp cli there. AFAIK the benefit to handle it within the requirements.txt is that renovate acts on it out of the box.

2023-12-13 11:46 UTC, praveenkumar commented
> need to add both the pulumi plugin for gpc and the gcp cli I only see the the pulumi plugin

Why I need to add `gcp` cli, I created the image using this container and able to create cluster using this image.

> that requirements is a way to manage tooling through pip if I am not wrong

But where are we using this requirements only for renovate?

2023-12-13 14:08 UTC, adrianriobo commented
> But where are we using this requirements only for renovate?

Not only for renovate we are using it as an unified way for pkg management (+ it is supported by renovate). 

So pros is we have a unified way to handle pkgs... cons is aws cli v2 is not supported there...on [qenvs](https://github.com/adrianriobo/qenvs/blob/5deb83aef211cc1dd9cda02e9782434b5b081a28/oci/Containerfile#L28) I use a different approach for each cli.

2023-12-13 14:13 UTC, adrianriobo commented
As a side note I realize you are using gcp classic provisioner https://github.com/pulumi/pulumi-gcp recently pulumi shift the way they create the provisioners to a native way using the cloud providers API https://github.com/pulumi/pulumi-google-native

It seems pulumi recommendation is to move to native provisioners...but they are not mature enough as an example I was able to use the azure native but not the aws as it misses still lot of resources... so add this as a comment we may can create a following issue as spike to migrate the gcp to the native provisioner WDYT?

2023-12-14 05:51 UTC, praveenkumar commented
> It seems pulumi recommendation is to move to native provisioners...but they are not mature enough as an example I was able to use the azure native but not the aws as it misses still lot of resources... so add this as a comment we may can create a following issue as spike to migrate the gcp to the native provisioner WDYT?

As per https://github.com/pulumi/pulumi-google-native looks like it is not stable and development is in active state so better to have follow up issue in case we want to switch over in near future.

2023-12-14 11:14 UTC, adrianriobo approved these changes

2023-12-14 11:14 UTC, merged