Infrastructure Deployment API implementation
crc-org/crc-cloud pull request #16
Opened 2023-01-10 15:41 UTC by tsebastiani

With this PR will be introduce the Infrastructure Deployer API in order to split the Infrastructure deployment logic from the Openshift Instance provisioning. This feature will simplify the proposed integrations with Terraform, Pulumi or even other custom deployment logic not yet mentioned giving to CRC-Cloud the ability to selectively loading the preferred logic with a CLI/ENV Parameter.
Even though bash is not an OO language, I created some functions to Enforce the correct API implementation and methods naming conventions.
Version bumped to 1.1 (maybe should be v2.0?)

2023-01-10 16:33 UTC, tsebastiani commented
I was wondering if "api" folder should be renamed "plugin", this is not actually containing the API but the implementations so probably plugin is more appropriate, thoughts?

2023-01-11 05:14 UTC, praveenkumar commented on crc-cloud.sh
>      [[ ( $WORKING_MODE == "T" ) && ($TEARDOWN_RUN_ID == "latest") ]] && stop_if_failed 1 "TEARDOWN_RUN_ID must be set in container mode. Please set this value with the run id that you want to teardow
Shouldn't this logic be part of `deployer/bash-aws/main.sh` otherwise adding more provider means we have to again use a logic to parse those. Instead `crc-cloud.sh` should be just entry point and require `deployer` and `platform` as of now default deployer can be `bash` and `platform` can be `aws` but if we able to make this separation now then it would be easy to rebase the `gcp` and `openstack` PR on top of it. 

Also I will create another PR from the commits of gcp provider PR which doesn't have any implementation around cloud provider but just some fix and breaking the logic.

2023-01-11 05:48 UTC, praveenkumar commented
I have create https://github.com/crc-org/crc-cloud/pull/17 which should be in and then this PR need to be rebased to make sure we have proper logic to add new cloud providers.

2023-01-11 08:06 UTC, tsebastiani commented on crc-cloud.sh
>      [[ ( $WORKING_MODE == "T" ) && ($TEARDOWN_RUN_ID == "latest") ]] && stop_if_failed 1 "TEARDOWN_RUN_ID must be set in container mode. Please set this value with the run id that you want to teardow
You're right, I missed it!

2023-01-11 09:35 UTC, tsebastiani commented on crc-cloud.sh
> +api_load_deployer $DEPLOYER_API
the position of this call was wrong, was loading the plugin before the -D argument was parsed resulting on always loading the default plugin

2023-01-11 11:38 UTC, lmilbaum commented
It is a good habit to have one commit (as atomic as possible) per PR. The following are just a few reasons why it is a good habit:
- Faster lead time (from open to merge)
- Lower risk for breaking the code
- Easier validation
- CI is run on every commit which is the only commit in the PR

2023-01-11 11:44 UTC, lmilbaum commented
A general question: is there a need for supporting multiple bootstrapping technologies? I am asking it because in my sense this project should be opinionated about the technology.

2023-01-11 15:47 UTC, tsebastiani commented
> 

You're right, I had to open this PR as a draft. It's actually a huge change that touched several parts of the code so even if made a single commit the review could have been not so comfortable.

2023-01-11 16:10 UTC, lmilbaum requested changes
I suggest to reconsider the approach of supporting multiple backend bootstrapping technologies

2023-03-02 05:40 UTC, praveenkumar commented
Closing this PR since we are going to use the pulumi and that would be default `main` branch.

2023-03-02 05:40 UTC, closed without merging