PASS_KUBEADMIN override in Container mode
crc-org/crc-cloud pull request #30
Opened 2023-01-24 15:28 UTC by tsebastiani

PASS_KUBEADMIN wasn't properly overridden in CONTAINER mode due to a typo in the variable check.
Figured out also that the last change made in the cloud provider selection wasn't working correctly in CONTAINER mode.

2023-01-25 07:15 UTC, praveenkumar requested changes

2023-01-25 07:15 UTC, praveenkumar commented on crc-cloud.sh
> +        [[ $? != 0 ]] && stop_if_failed 1 "[DEPENDENCY MISSING]: aws cli, please install it and try again"
These changes shouldn't part of this commit. Looks like it is just whitespace changes.

2023-01-25 07:15 UTC, praveenkumar commented on crc-cloud.sh
> +    [[ $? != 0 ]] && stop_if_failed 1 "[DEPENDENCY MISSING]: aws cli, please install it and try again"
If we are using containerize environment then should those dep should be part of container image or on the host? I am hoping it should be part of container image.

2023-01-25 07:15 UTC, praveenkumar commented on crc-cloud.sh
> -pr_info "CLOUD PROVIDER $CLOUD_PROVIDER"
Then it should be removed in previous commit itself.

2023-01-25 08:32 UTC, tsebastiani commented on crc-cloud.sh
> +    [[ $? != 0 ]] && stop_if_failed 1 "[DEPENDENCY MISSING]: aws cli, please install it and try again"
That's a good point, we might include those variables in the Dockerfile as ENV, what do you think?

2023-01-25 08:32 UTC, tsebastiani commented on crc-cloud.sh
> +        [[ $? != 0 ]] && stop_if_failed 1 "[DEPENDENCY MISSING]: aws cli, please install it and try again"
yeah, sorry

2023-01-25 09:06 UTC, praveenkumar commented on crc-cloud.sh
> +    [[ $? != 0 ]] && stop_if_failed 1 "[DEPENDENCY MISSING]: aws cli, please install it and try again"
@tsebastiani why do we want to add these as env variable also? Since we are already creating the container image so we can make a fair assumption about those dependencies already part of that image instead again checking with `which` right?

2023-01-25 09:58 UTC, tsebastiani commented on crc-cloud.sh
> +    [[ $? != 0 ]] && stop_if_failed 1 "[DEPENDENCY MISSING]: aws cli, please install it and try again"
The only problem that I see with this approach is that we have to hardcode the paths of the binaries and if they're changed in the package that we install (very unlikely actually for dnf, not sure for the aws cli that comes from pip) this will break the build, that's the reason why of the which check.

2023-02-07 09:16 UTC, lmilbaum commented on crc-cloud.sh
> +    [[ $? != 0 ]] && stop_if_failed 1 "[DEPENDENCY MISSING]: aws cli, please install it and try again"
I like @praveenkumar approach of baking the container image with all the dependencies. If I am not mistaken, path issues can be resolved by setting the PATH environment variable in the container image.

2023-02-07 10:26 UTC, tsebastiani commented on crc-cloud.sh
> +    [[ $? != 0 ]] && stop_if_failed 1 "[DEPENDENCY MISSING]: aws cli, please install it and try again"
I don't get the point, I can for example, point the AWS cli variable to ```/usr/bin/aws``` in the Dockerfile  and will be fine, but what if pip tomorrow will change the path where the binary is installed (very unlikely but possible)? For that reason I was using `which` instead of setting the paths in the script.

2023-02-07 11:44 UTC, tsebastiani commented on crc-cloud.sh
> +    [[ $? != 0 ]] && stop_if_failed 1 "[DEPENDENCY MISSING]: aws cli, please install it and try again"
absolutely

2023-03-02 05:40 UTC, praveenkumar commented
Closing this PR since we are going to use the pulumi and that would be default main branch.

2023-03-02 05:40 UTC, closed without merging