added README information for usage of crc-cloud based on pulumi.
crc-org/crc-cloud pull request #35
Opened 2023-02-02 21:21 UTC by adrianriobo

this PR will introduce specific information on how to operate with crc-cloud container images for crc-cloud based on pulumi implementation

2023-02-07 09:12 UTC, lmilbaum commented
Can't test this PR. I am blocked because it doesn't support the region I am working with `eu-west-2`.  What are the required steps to support another region?

2023-02-13 15:05 UTC, lmilbaum commented
Could you change the file arguments (pull secret and key)  to in-memory ones? The file content is a secret. I would like to avoid manipulating the secrets before the environment is spinned. Take a look at the following PR - https://github.com/platform-engineering-org/poc/pull/93

2023-02-13 15:06 UTC, lmilbaum requested changes
Could you change the file arguments (pull secret and key) to in-memory ones? The file content is a secret. I would like to avoid manipulating the secrets before the environment is spinned. Take a look at the following PR - https://github.com/platform-engineering-org/poc/pull/93

2023-02-17 08:59 UTC, adrianriobo commented
Add general information on `auth` mechanisms for AWS inherit from `pulumi` so from AWS itself. 

- default credentials
- short-lived credentials
- config file / profile

2023-03-01 05:59 UTC, praveenkumar commented on README.md
> +        --pullsecret-filepath "/workspace/pullsecret" \
This is coming from bundle and it is used for sshing to the instance after it created. By default AMI have this key configured and same the openshift cluster which is why this is a requirement. @adrianriobo you might add this details here.

2023-03-01 09:00 UTC, adrianriobo commented on README.md
> +        --pullsecret-filepath "/workspace/pullsecret" \
Here there is a comment about it..https://github.com/adrianriobo/crc-cloud/tree/pulumi_readme#import I think that should be enough. Otherwise I would go too deep on explaining every detail on the import / create flow (which actually is described within the diagram). 

If a full explanation on it is required I am ok with it but it would go on a different `md` and probably could be tackle on a different PR

2023-03-01 09:01 UTC, adrianriobo commented on README.md
>      -e AWS_ACCESS_KEY_ID=XXX \
Added as `envs` on samples...it is showing some values for it...and it is up to the user how you set them up.

2023-03-01 09:02 UTC, adrianriobo commented on README.md
> +Previous command mount the current folder into the container `/worspace` which then it is used as `output` for resulting assets for the import operation. The assets generated will be:
This part was removed during the latest update

2023-03-01 14:26 UTC, praveenkumar commented
/lgtm

2023-03-01 14:31 UTC, merged